spring.application.name=itsutraa

# DATABASE CONFIGURATION
spring.datasource.url=mysql://avnadmin:AVNS_vqZrXMQcGXXDvAwsZKE@mysql-1efb2c37-itsutraa.h.aivencloud.com:21213/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_vqZrXMQcGXXDvAwsZKE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HIBERNATE & JPA (Force dialect to bypass metadata error)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SERVER
server.port=8080

# THYMELEAF
spring.thymeleaf.cache=false

# RAZORPAY TEST MODE
razorpay.key.id=${KEY_ID}
razorpay.key.secret=${KEY_SECRET}

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=
app.base-url=http://localhost:8080
app.environment=development

# SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
